# Generated by Django 4.2.30 on 2026-09-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('000', '000 – Generalidades e Informação: Obras gerais, enciclopédias, jornais e biblioteconomia.'), ('100', '100 – Filosofia e Psicologia: Ética, lógica e investigações sobre a mente humana.'), ('200', '200 – Religião e Teologia: Mitologia, teologia e estudos sobre crenças e religiões.'), ('300', '300 – Ciências Sociais e Direito: Política, economia, sociologia, educação e leis.'), ('400', '400 – Linguística e Idiomas: Gramáticas, dicionários e estudos de línguas.'), ('500', '500 – Ciências Puras (Exatas e Naturais): Matemática, física, química, biologia e astronomia.'), ('600', '600 – Ciências Aplicadas (Tecnologia): Medicina, engenharia, agricultura e administração.'), ('700', '700 – Artes e Recreação: Pintura, música, arquitetura, esportes e lazer.'), ('800', '800 – Literatura: Poesia, romances, contos, crônicas e crítica literária.'), ('900', '900 – História e Geografia: Biografias, viagens e acontecimentos históricos.')], default='000', max_length=3, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital')], default='FISICO', max_length=10, verbose_name='Tipo de Acervo'),
        ),
    ]
